name: Coverage
on:
  pull_request:
    branches: [ "**" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Run tests + Kover XML
        run: ./gradlew koverXmlReport --no-daemon
      - name: Add coverage report to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/app/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80